### PR TITLE
Feature: revise raw data filtering steps based on FLASC PR #78

### PR DESCRIPTION
**Pull request by Bartdoekemeijer**
This revises the data filtering steps related to FLASC pull request #78. Most notably:

- Uses the most generic data filtering functionality in FLASC #78.
- Adds additional filtering steps and comments that may be useful for other data.
- Adds more explicit figures about when a fault occurs.

### CODE REVIEW

**Comment by misi9170** [comment]
Thanks @Bartdoekemeijer! I'm looking into this and your PR on FLASC now. I'm new to cruft though.... is there a way I can 'pull' down this pull request (or link to your fork, and then checkout this branch) into an existing cruft instance of the flasc_cookiecutter_template? Or do I need to create a new instance from [your fork and branch](https://github.com/Bartdoekemeijer/flasc_cookiecutter_template/tree/feature/revise_turbine_filtering)?

**Comment by Bartdoekemeijer** [comment]
@misi9170 I'm not sure if you can do that. Theres a `cruft.json` file in the top folder of the repository which may allow you to change the remote repository and branch to my pull request, but I haven't tried that myself. Normally, you can run `cruft update` to pull in the latest changes from the `main` branch, but I'm not sure if there's a convenient way of doing things for PRs/other branches. There may be, see https://github.com/cruft/cruft/issues/24, but instructions are not very clear.

**Comment by misi9170** [comment]
Thanks @Bartdoekemeijer! I did see that issue and the PR that closed it. However, as I understand it, that's just for other branches on the base repo, not for adding forks. So, I think the best course of action for me is to just instantiate a new cruft instance from your fork and branch.

**Comment by misi9170** [comment]
@Bartdoekemeijer all looks good to me. I'm going to go ahead and merge directly to main here.

**Pull request merged**
